### ISSUE TITLE
Slow gas price higher than normal

### ISSUE THREAD

**Issue by shark0der** [wslyvh/ethgaswatch#4] opened 2020-10-04 18:31 UTC
Witnessed this today:
![photo_2020-10-04_21-25-26](https://user-images.githubusercontent.com/528959/95023872-28842580-0688-11eb-89d4-cc5e9dba0ef2.jpg)

Looking at the charts it seems like this happens often:
![image](https://user-images.githubusercontent.com/528959/95023955-be1fb500-0688-11eb-84e9-9442de28380d.png)

It's possible that these are 2 separate issues, you could analyze the data and see what happens exactly.

**Comment by wslyvh** [comment] 2020-10-05 10:49
Yes, it happens quite often. This is not a bug on the application side, unfortunately. All data is coming from API's and external data sources. 

I'll try and see to filter out sources where the values are off. So the average prices should at least be correct all the time.

**Comment by wslyvh** [comment] 2020-10-06 09:12
I've added an additional check to filter out the source if the values are wrongly ordered. 
It's still possible for above to happen, but this should greatly reduce the chances. 

It doesn't update the current data/charts though, so will only be reflected in the future graphs.

Will close it for now.

**Closed by wslyvh** 2020-10-06 09:12 UTC
Labels: bug, good first issue, help wanted

**Comment by teohhanhui** [comment] 2021-01-11 18:26
Since it's aggregating values from different sources, just taking some statistical average for each level is not enough. All the different levels need to be taken together as a distribution, otherwise it doesn't make sense.

See #5.
